
--- FIND OUT THE DEPARTMENT_NAME
--  AND THE MANAGER FIRST_NAME FOR EACH DEPARTMENTS
-- FACT : MANAGER_ID COLUMN OF DEPARTMENTS TABLE
--- IS THE EMPLOYEE_ID OF THAT MANAGER
-- ACCORDING TO THE DEPARTMENT TABLE MANAGER COLUMN COMMENT
--- MANAGER_ID IS FOREIGN KEY TO EMPLOYEE_ID OF EMPLOYEE COLUMN
--- IN A NUTSHELL , THAT IS THE RELATIONSHIP WE ARE GOING TO USE
---  EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.MANAGER_ID
 -- NOTE THAT COLUMN NAMES DOES NOT HAVE TO MATCH AS LONG AS RELATIONSHIP IS DEFINED

SELECT DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.FIRST_NAME
FROM DEPARTMENTS
INNER JOIN EMPLOYEES
ON DEPARTMENTS.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID ;
--- this is alias version
SELECT d.DEPARTMENT_NAME, e.FIRST_NAME
FROM DEPARTMENTS d
INNER JOIN EMPLOYEES e ON d.MANAGER_ID = e.EMPLOYEE_ID ;


----  CONTINUE FROM ABOVE QUERY, FIND OUT THE MANAGER FIRST_NAME OF Executive
SELECT d.DEPARTMENT_NAME, e.FIRST_NAME
FROM DEPARTMENTS d
INNER JOIN EMPLOYEES e ON d.MANAGER_ID = e.EMPLOYEE_ID
WHERE d.DEPARTMENT_NAME = 'Executive'
;

-- FIND OUT THE DEPARTMENT_NAME
--  AND THE MANAGER FIRST_NAME FOR EACH DEPARTMENTS
----  ONLY DISPLAY IF DEPARTMENT_NAME START WITH A
--WHERE d.DEPARTMENT_NAME LIKE 'A%';

--- FIND OUT HOW MANY COUNTRY IN EACH REGION
SELECT REGION_ID , COUNT(*)
FROM COUNTRIES
GROUP BY REGION_ID ;

--- FIND OUT HOW MANY COUNTRY IN EACH REGION
--- DISPLAY REGION_NAME AND COUNTRY_COUNT
SELECT REGIONS.REGION_NAME , COUNT(COUNTRIES.COUNTRY_NAME) AS "COUNTRY_COUNT"
FROM COUNTRIES
INNER JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
GROUP BY REGIONS.REGION_NAME ;



