/**
  These query will generate 2 tables
  with name FIRST_TABLE and SECOND_TABLE
  They have 2 columns FIRST_NAME, SALARY
  FIRST_TABLE has 10 ROWS OF DATA
  SECOND_TABLE has 9 ROWS OF DATA
  4 ROWS OF DATA ARE COMMON IN BOTH TABLES
 */

CREATE TABLE FIRST_TABLE AS (
    SELECT FIRST_NAME , SALARY FROM EMPLOYEES
    WHERE SALARY BETWEEN 10500 AND 13000

) ORDER BY 2 ;


CREATE TABLE SECOND_TABLE AS (
    SELECT FIRST_NAME , SALARY FROM EMPLOYEES
    WHERE SALARY BETWEEN 12000 AND 24000

) ORDER BY 2 ;

COMMIT ;
